name: Deploy Cloud Function

on:
  push:
    branches:
      - master # Vagy a kívánt branch neve

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: jobbszamlazo # A Google Cloud projekted azonosítója
          service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JOBBSZAMLAZO }} # A titkosított service account kulcs
          export_default_credentials: true # Ez exportálja a hitelesítési adatokat a környezetbe

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy generatePdfFromUrl \ # A helyes függvénynév
            --runtime nodejs18 \
            --trigger-http \
            --source . \
            --allow-unauthenticated # Ez lehetővé teszi a függvény hívását hitelesítés nélkül (opcionális)